"""добавил account_number

Revision ID: 843853ac413d
Revises: a38bf83aa991
Create Date: 2026-05-03 13:27:08.663076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843853ac413d'
down_revision: Union[str, Sequence[str], None] = 'a38bf83aa991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'accounts', ['account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'account_number')
    # ### end Alembic commands ###
