"""empty message

Revision ID: be881b586dfa
Revises: 79f480745a91
Create Date: 2026-05-07 10:06:26.718393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be881b586dfa'
down_revision: Union[str, Sequence[str], None] = '79f480745a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('from_account_number', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('to_account_number', sa.String(), nullable=False))
    op.drop_constraint(op.f('transactions_to_account_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_from_account_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['from_account_number'], ['account_number'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['to_account_number'], ['account_number'])
    op.drop_column('transactions', 'from_account_id')
    op.drop_column('transactions', 'to_account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('to_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('from_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_from_account_id_fkey'), 'transactions', 'accounts', ['from_account_id'], ['id'])
    op.create_foreign_key(op.f('transactions_to_account_id_fkey'), 'transactions', 'accounts', ['to_account_id'], ['id'])
    op.drop_column('transactions', 'to_account_number')
    op.drop_column('transactions', 'from_account_number')
    # ### end Alembic commands ###
